_target_: src.models.rnn.RNNModel
_name_: rnn_model

d_model: 256
num_layers: 1
output_mode: state  # state, sequence, last
bidirectional: false

cell:
  cell_type: rnn  # rnn, gru, lstm
  hidden_activation: tanh
  orthogonal: false
  dropout: 0.0