_target_: src.models.sequence.rnns.rnn.RNN
_name_: RNNModel

d_model: 256
num_layers: 1
output_mode: state  # state, sequence, last
bidirectional: false

cell:
  cell_type: rnn  # rnn, gru, lstm
  hidden_activation: tanh
  orthogonal: false # orthogonal initialization
  dropout: 0.0