defaults:
  - layer: ncps_ltc
#_target_: src.models.sequence.SequenceModel
_name_: sequence

n_layers: 1
d_model: 64
prenorm: true
transposed: false
residual: null
pool:
  _name_: pool
  stride: 1
  expand: 1
norm: layer
dropout: 0.0
tie_dropout: false
track_norms: true # Logs to wandb

# Optional encoder/decoder, e.g. add positional embeddings or padding masks
encoder: null
decoder: null