#defaults:
#  - cell: ncps_ltc

_name_: ltc_for_ncps
#input_size: 28
ode_unfolds: 6

units: 
  - name: AutoNCP
  - units: 64
  - output_units: 10

return_sequences: True
batch_first:  True
mixed_memory: False
input_mapping: "affine"
output_mapping: "affine"

epsilon: 1e-8
implicit_param_constraints: True